### ISSUE TITLE
Takes care of narrowing

### ISSUE THREAD

**Issue by DamienCassou** [DamienCassou/beginend#22]
`beginning-of-buffer` uses the beginning of the accessible part of the buffer if buffer is narrowed. I guess `beginend` should do the same. 

It may already work properly but we should check.

**Comment by DamienCassou** [comment]
I have the impression that the best approach would be to go to `(point-min)` or `(point-max)` when narrowing is in effect.

**Comment by Fuco1** [comment]
But don't we already use `point-min` and `point-max`?  That is the correct approach, they resolve to whatever is available in the current buffer narrowing.

**Comment by DamienCassou** [comment]
Exactly, but our code will still try to find a better beginning/end. I think it should not if the buffer is narrowed. So, my current opinion is to implement something like:

```
if narrowing
   execute {beginning,end}-of-buffer interactively
else
  do whatever we currently do
```

**Comment by Fuco1** [comment]
Oh I see.  Yes that sounds reasonable, in narrowed context you probably want to jump to the narrowing edge instead of (possibly randomly) jump somewhere else as the context assumptions might not hold there.
