### ISSUE TITLE
beginend does not work in message mode anymore

### ISSUE THREAD

**Issue by DamienCassou** [DamienCassou/beginend#32]
Apparently, message-mode (at least when answering an email from notmuch) is automatically narrowed and beginend deactivates itself in narrowed buffers.

Step to reproduce;

1. open notmuch
2. open an email
3. press `r` to reply
4. `M-: (buffer-narrowed-p)` answers true

**Comment by DamienCassou** [comment]
The narrowing comes from function `message-hide-headers` and variable `message-hidden-headers`.

Should we change our narrowing algorithm so that it first widens the buffer, then moves point and then narrow again? I have no clue if that can work in practice.

**Comment by Fuco1** [comment]
Seems like in this particular case it should work as you describe, but I don't think that's a generally working solution (sometimes you can narrow even in the middle of syntax change and then things might get funny).

Maybe some exception list for buffers/modes where we want to work even if narrowed would be simpler and more maintainable.

**Comment by DamienCassou** [comment]
> I don't think that's a generally working solution (sometimes you can narrow even in the middle of syntax change and then things might get funny)

I don't understand why it would not work (and I don't know anything about "syntax change"). Can you please explain?

**Comment by Fuco1** [comment]
Imagine you have a buffer

```c
/*
 *
 *
 */

code starts here

...

..
```

If you narrow from the middle of the comment it is no longer a comment (eventhough the font-locker will probably not un-fontify it since why would it:P).  So if you cut somewhere where syntactically the form starts *outside* the narrowing it will break the parser.

So for example the `prog-mode` beginend would fail here.

**Comment by DamienCassou** [comment]
Because I was not sure to understand, I implemented it in https://github.com/DamienCassou/beginend/pull/33. Can you please show me how to make my code fail? I couldn't, even in prog-mode in a JavaScript buffer looking like that after narrowing:

```javascript
 * Coucou
 */
let animal = klassified.object.abstractSubclass((that, my) => {
	that.alert = function() {
		return my.subclassResponsibility();
	};
});
```

**Comment by Fuco1** [comment]
Suppose I have this

```js
/*
 * Coucou
 */
let animal = klassified.object.abstractSubclass((that, my) => {
	that.alert = function() {
		return my.subclassResponsibility();
	};
});


/*
 * Coucou
 */
let animal = klassified.object.abstractSubclass((that, my) => {
	that.alert = function() {
		return my.subclassResponsibility();
	};
});
```

With the narrowing as you have shown above but on the *second* block.  Then we would not end after the comment but on top of the buffer no? Because when the buffere is widened point would go after the first comment but then re-narrowing would just move it to `point-min` which would be the line with `* Coucou`.

**Comment by DamienCassou** [comment]
The point would go to `point-min` in your example (which is inside 2nd comment) and that's what I expect because, for me, beginend is supposed to analyze beginning and end of complete buffers, not any buffer portion. This is what we have implemented in all our plugins (calls to `beginend-define-mode`). All of them suppose the buffer is widen.

We then have to make a decision if a plugin

1. should sense of text wherever `point-min`/`point-max` are, or
2. can suppose buffer is widen.

I'm in favor of (2) but I'm open to discussion if you think (1) is feasible. If we go for (2), my approach on #33 seems ok.

**Comment by Fuco1** [comment]
Yes, I suppose 2 is better.  Magic should only happen if you are viewing the entire buffer, I agree.

**Comment by DamienCassou** [comment]
Is #33 mergeable then? Do you want to have a closer look at it before?
