### ISSUE TITLE
Should go to start or end of line when going to end?

### ISSUE THREAD

**Issue by DamienCassou** [DamienCassou/beginend#34]
In some modes, `beginend` goes to the beginning of the last line (e.g., `prodigy`, `ibuffer`) and in some others it goes to the end of the last line (e.g., `dired`, `notmuch-search`). I think it should always go to the end of the last line because this is what `beginning-of-buffer` does but I'm open to discussion.

/cc @Fuco1

**Comment by Fuco1** [comment]
Personally I prefer if it goes to the end when there might be some reason to expect I want to copy the region.  For buffers like `dired`, `ibuffer`, `magit` I think it would be visually more pleasing to go to the beginning of line.  That way the cursor stays "in line" (or rather in column) when jumping up and down and it does not behave so erratically.

**Comment by DamienCassou** [comment]
What about going to the beginning of line each time the major mode inherits from `special-mode` and end of line the rest of the time?

**Comment by Fuco1** [comment]
That should cover most cases probably, good idea.

**Comment by DamienCassou** [comment]
Here are the potential problems of this approach:

- in dired-mode, I want the cursor at the start of the filename, not the start of line
- in occur-mode, current behavior moves point at match (but having point at beginning of line is ok for me too)
- in prodigy-mode, I would like to go `back-to-indentation`.

What do you think?

**Comment by Fuco1** [comment]
Well in dired one can call `(dired-move-to-filename)` to move the point there.  I think this will just need to be handled on a per-mode basis.
