### ISSUE TITLE
Alway go to end|begin of line?

### ISSUE THREAD

**Issue by TLINDEN** [DamienCassou/beginend#49]
Hi,

I use this [function](https://rawgit.com/TLINDEN/dot-emacs/master/emacs.html#org5e825ea) now for about 20 years and today stumbled on your mode. My version just jumps to end-of-line => end-of-window => end-of-buffer, it's not mode agnoistic, so I'd like to replace it with your mode.

However, I'm so used to jumping to end of line first that I can't just give it up :) So, my question is, would this be possible using your mode? Like if you are editing an elisp file - first key hit: jump to end of current sexp, next: jump to end of line, next: jump to end of defun (or if not visible in the current window: end of window first!), next: end of buffer.

Thanks in advance,
Tom

**Comment by DamienCassou** [comment]
Hi Tom.

The `beginend` package goes back to its previous location when the same key is typed again. This seems to conflict a bit with your idea of multiple ends the cursor could visit in turn.

What about adding a separate set of commands that would work the way you suggest and reuse the definitions for mode-specific limits? I'm ok to merge a PR containing such a feature into beginend if you also take care of explaining the new feature in the README.

**Comment by DamienCassou** [comment]
I've just found that which might be related: https://github.com/Boruch-Baum/emacs-home-end.

**Comment by TLINDEN** [comment]
This is what I have now, although I wrote it myself.

**Comment by DamienCassou** [comment]
I'm closing this. Feel free to reopen if there is anything new.
