### ISSUE TITLE
Going to the beginning of an Org buffer fails if there is any text before the first heading

### ISSUE THREAD

**Issue by oantolin** [DamienCassou/beginend#56]
In Org buffers `M-<` seems to only work if the buffer starts with a `*`. When it fails it does so with the message:

    Invalid function: org-with-limited-levels

It fails for (1) an empty Org buffer, (2) a buffer containing just `a`, (3) a buffer that has `* a` as the _second_ line after an empty first line, (4) a buffer with, say a title:

    #+TITLE: a

    * b

I think it might be due to the declaration `(declare-function org-with-limited-levels "org-macs")`. My theory is that that tells the byte compiler to emit a function call sequence for `org-with-limited-levels`, but since it's actually a macro and not a function, this causes the invalid function error.

It seems that simply commenting out the declaration fixes the problem and causes no warning from the byte-compiler, but I'm not sure if that's the right fix.

**Comment by DamienCassou** [comment]
Thank you for your report. I have tried to ignore the problem for too long :-).

Can you please check https://github.com/DamienCassou/beginend/pull/57?

**Comment by oantolin** [comment]
That certainly fixes the problem, thank you! (I tested in all the cases I had tested before.) And I'm particularly happy about the addition of:

```elisp
    (when (eobp)
      (setf (point) (point-min))))
```

I was thinking of adding that myself, because in the odd case of no headings at all, it seemed wrong to leave the point at the end.

(By the way, I didn't know `(point)` had a setter, cool! Although `(goto-char (point-min))` is both shorter and seems more Emacsy.)

**Comment by DamienCassou** [comment]
thank you for testing. I merged the PR.

> Although `(goto-char (point-min))` is both shorter and seems more Emacsy

I agree with both points. Nevertheless, I'm slowly learning to use `setf` as much as possible because this is less vocabulary to learn and remember. Regarding "seems more Emacsy", my plan is that everyone uses `setf` so it becomes Emacsyer :-D.

**Comment by oantolin** [comment]
I really like `setf`, in Common Lisp it's the idiomatic way to do things like this, and I am on board with your plane to make it more idiomatic in Emacs Lisp too.

**Comment by duckwork** [comment]
Hello,

I'm commenting on this because I want to note that for me, on Windows 10 and Emacs 27.2, the `(setf (point) (point-min))` idiom doesn't work.  I get an error:

```
﻿beginend-org-mode-goto-beginning: Symbol’s function definition is void: \(setf\ point\)
```

Changing the definition to `(goto-char (point-min))` fixes the issue.

Let me know if I need to open a fresh issue for this.

**Comment by DamienCassou** [comment]
@duckwork thank you for your message. Does `(setf (point) (point-min))` work after you `M-: (require 'cl-lib) RET`?

**Comment by duckwork** [comment]
Hmm, yes.  Which is pretty strange!
