### ISSUE TITLE
Should beginend consider module docstrings in python buffers?

### ISSUE THREAD

**Issue by doolio** [DamienCassou/beginend#77]
I have `beginend-global-mode` enabled and `begined-prog-mode` is enabled in a python buffer. However, `M-<` treats  a module docstring as the first line of code but should it perhaps not?  It does so even if the shebang line is not present. I don't know if other languages have an equivalent of a python module docstring so this may not be limited to python. No such issue in an elisp buffer as the package header text is demarcated in the same way as a normal comment.

```
#!/usr/bin/env python3

"""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

"""

# Code starts after this comment.
```

**Comment by DamienCassou** [comment]
I think what you suggest makes perfect sense. Would you mind sending a PR with unit tests to fix this? I think we could change `beginend--prog-mode-code-position-p` to add a call to `beginend--point-is-in-string-p` (to be implemented).

**Comment by doolio** [comment]
I can certainly try but it may take me some time. I'm still very much a beginner. Thanks for the pointers on how I could go about this.
